# Generated by Django 2.0.3 on 2023-05-28 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True)),
                ('slug', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('solution', models.TextField(null=True)),
                ('search_count', models.IntegerField(null=True)),
                ('is_input_required', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
