# Generated by Django 2.0.3 on 2023-06-06 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='learn_or_practice',
            field=models.IntegerField(default=0, help_text='0=Learn, 1=practice'),
        ),
    ]
