# Generated by Django 2.0.3 on 2023-04-08 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20230408_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='slug',
            field=models.TextField(),
        ),
    ]
