# Generated by Django 2.0.3 on 2023-04-08 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20230408_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='solution',
        ),
        migrations.AlterField(
            model_name='questions',
            name='slug',
            field=models.TextField(null=True),
        ),
    ]
