# Generated by Django 2.0.3 on 2023-05-15 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20230408_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='search_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='solution',
            field=models.TextField(null=True),
        ),
    ]
