# Generated by Django 4.2.5 on 2023-10-01 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_alter_questions_options_alter_learn_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codes', models.TextField(null=True)),
                ('learn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.learn')),
            ],
            options={
                'verbose_name_plural': 'Learn Codes',
            },
        ),
    ]
