# Generated by Django 4.2 on 2023-05-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20230515_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='is_input_required',
            field=models.IntegerField(null=True),
        ),
    ]
