# Generated by Django 4.2.5 on 2023-10-15 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_learncodes_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learn',
            name='codes',
        ),
        migrations.RemoveField(
            model_name='learn',
            name='is_input_required',
        ),
        migrations.AddField(
            model_name='learncodes',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='learncodes',
            name='is_input_required',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='learncodes',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='learncodes',
            name='link',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Identifier'),
        ),
    ]
