# Generated by Django 4.2 on 2023-05-24 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_questions_is_input_required'),
    ]

    operations = [
    ]
