# Generated by Django 4.2.5 on 2023-10-15 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_remove_learn_codes_remove_learn_is_input_required_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='learn_or_practice',
        ),
    ]
