# Generated by Django 4.2.5 on 2023-10-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_alter_learn_search_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learncodes',
            name='is_input_required',
            field=models.IntegerField(default=0, help_text='0=No, 1=Yes'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='is_input_required',
            field=models.IntegerField(default=0, help_text='0=No, 1=Yes'),
        ),
    ]
